version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_jadwalin
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=bantengmerah